services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./training:/app/training
      - ./streamlit_app:/app/streamlit_app
      - ./data.xlsx:/app/data.xlsx
    env_file:
      - .env
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./streamlit_app:/app/streamlit_app
      - ./api:/app/api
      - ./training:/app/training
      - ./data.xlsx:/app/data.xlsx
    env_file:
      - .env
    environment:
      API_URL: "http://api:8000/predict/single"
    restart: unless-stopped
